import type { Commentary, Matches } from "@/types";

export const MATCHES: Matches[] = [
  {
    id: 1,
    sport: "Football",
    homeTeam: "Manchester United",
    awayTeam: "Liverpool",
    startTime: "2026-02-05T15:00:00",
    endTime: "2026-02-05T16:45:00",
    homeScore: 2,
    awayScore: 1,
  },
  {
    id: 2,
    sport: "Cricket",
    homeTeam: "India",
    awayTeam: "Pakistan",
    startTime: "2026-02-05T09:30:00",
    endTime: "2026-02-05T17:30:00",
    homeScore: 287,
    awayScore: 245,
  },
  {
    id: 3,
    sport: "Basketball",
    homeTeam: "Los Angeles Lakers",
    awayTeam: "Boston Celtics",
    startTime: "2026-02-05T19:00:00",
    endTime: "2026-02-05T21:30:00",
    homeScore: 112,
    awayScore: 108,
  },
  {
    id: 4,
    sport: "Tennis",
    homeTeam: "Novak Djokovic",
    awayTeam: "Carlos Alcaraz",
    startTime: "2026-02-05T14:00:00",
    endTime: "2026-02-05T16:20:00",
    homeScore: 2,
    awayScore: 1,
  },
  {
    id: 5,
    sport: "Baseball",
    homeTeam: "New York Yankees",
    awayTeam: "Boston Red Sox",
    startTime: "2026-02-05T20:00:00",
    endTime: "2026-02-05T22:45:00",
    homeScore: 5,
    awayScore: 3,
  },
  {
    id: 6,
    sport: "Rugby",
    homeTeam: "All Blacks",
    awayTeam: "Springboks",
    startTime: "2026-02-05T12:00:00",
    endTime: "2026-02-05T13:40:00",
    homeScore: 24,
    awayScore: 22,
  },
];

export const COMMENTARY: Commentary[] = [
  {
    matchId: 3,
    minute: 14,
    sequence: 654,
    period: "1st innings",
    eventType: "boundary",
    team: "India",
    actor: "Rohit Sharma",
    message: "Rohit Sharma cuts it past point for a FOUR.",
    tags: ["four", "boundary"],
  },
  {
    matchId: 3,
    minute: 16,
    sequence: 655,
    period: "1st innings",
    eventType: "six",
    team: "India",
    actor: "Virat Kohli",
    message: "Massive hit! Kohli launches it over long-on for SIX.",
    tags: ["six", "maximum"],
  },
  {
    matchId: 3,
    minute: 18,
    sequence: 656,
    period: "1st innings",
    eventType: "wicket",
    team: "India",
    actor: "Jasprit Bumrah",
    message: "WICKET! Bumrah removes the batsman with a sharp bouncer.",
    tags: ["wicket", "out"],
  },
  {
    matchId: 3,
    minute: 20,
    sequence: 657,
    period: "1st innings",
    eventType: "dot",
    team: "India",
    actor: "KL Rahul",
    message: "Good length delivery, defended back to the bowler.",
    tags: ["dot", "no-run"],
  },
  {
    matchId: 3,
    minute: 22,
    sequence: 658,
    period: "1st innings",
    eventType: "run",
    team: "India",
    actor: "Shubman Gill",
    message: "Quick running between the wickets, they take TWO runs.",
    tags: ["run", "two"],
  },
  {
    matchId: 3,
    minute: 25,
    sequence: 659,
    period: "1st innings",
    eventType: "drinks",
    team: "India",
    actor: "Umpire",
    message: "Drinks break called as players head off the field.",
    tags: ["break", "drinks"],
  },
];
